echo ""
echo ""
echo ""
echo -e "\e[1;36m$ Hey user 😇\e[0m"
sleep 2
echo ""
echo -e "\e[1;36m$ I am MASTERMIND (Fusion_spirite) \e[0m"
sleep 2
echo ""
echo -e "\e[1;36m$ If you are having trouble then contact me  \e[0m"
echo -e "\e[1;36m$→Telegram = t.me/Fusion_Spirite\e[0m"
echo -e "\e[1;34m$→Telegram group = https://t.me/Omniversal_creations_chat\e[0m"
sleep 2
echo ""
echo -e "\e[1;34m==================================\e[0m"
echo -e "\e[1;36m× If you dont know how to use extractor. \e[0m"
echo -e "\e[1;35m× Watch this : "
echo -e "\e[1;34m==================================\e[0m"
sleep 2
echo ""
echo -e "\e[1;34m==================================\e[0m"
echo -e "\e[1;36m× Releas date | FRI - 31 - JAN - 2025\e[0m"
echo -e "\e[1;36m× Version code | 2\e[0m"
echo -e "\e[1;36m× Version | 1.0.2\e[0m"
echo -e "\e[1;36m× Releas | Second.\e[0m"
echo -e "\e[1;34m==================================\e[0m"
echo ""
echo -e "\e[1;36mTHANKS FOR USING 😊 enjoy creation. \e[0m"
echo ""
echo -e "\e[1;34m==================================\e[0m"
sleep 2
echo ""
echo -e "\e[1;37mɪғ ᴍʏ sᴄʀɪᴘᴛ ʜᴇʟᴘs ʏᴏᴜ ɪɴ ʏᴏᴜʀ ᴍᴏᴅᴜʟᴇ\e[0m"
echo -e "\e[1;37mᴛʜᴇɴ ᴘʟᴇᴀsᴇ ᴍᴀᴋᴇ sᴜʀᴇ ᴛʜᴀᴛ ʏᴏᴜ ɢɪᴠᴇ \e[0m"
echo -e "\e[1;37mʟɪᴛᴛᴇʟ ʙɪᴛ ᴄʀᴇᴅɪᴛ ᴏғ ᴍɪɴᴇ ᴛᴏ ᴍᴇ. \e[0m"
sleep 1
echo ""
echo -e "\e[1;37mᴀʟsᴏ ᴊᴏɪɴ ᴍʏ ᴛᴇʟᴇɢʀᴀᴍ ɢʀᴏᴜᴘ ᴏʀ ᴄʜᴇɴɴᴇʟ\e[0m"
echo -e "\e[1;37mғᴏʀ ᴍᴏʀᴇ ᴍᴏᴅᴜʟᴇs. \e[0m"
